### PR TITLE
fix: Replaced old thunderhack website

### PR DESCRIPTION
**Pull request by cvs0**

### CODE REVIEW

**Review by Zane2b2t — APPROVED** [review]

**Comment by Pan4ur** [comment]
It's still early. At the very least we need to change the video on the website xd

**Comment by cvs0** [comment]
Ah shit, I thought this PR was merged and committed the addon system 😂

**Comment by cvs0** [comment]
> It's still early. At the very least we need to change the video on the website xd

We will get on that soon, can you send me the new video?

**Comment by Pan4ur** [comment]
Put up a demo video, like a fish text, I'll get someone to make us a video

**Pull request merged**
